def clumpfinding(Text,k,L,t):
    pattern = []
    n = len(Text)
    for i in range(n-L+1):
        window = Text[i:i+L]
        freqmap = FrequencyMap(window,k)
        for key in freqmap:
            if freqmap[key] >= t and key not in pattern:
                pattern.append(key)
    return pattern
def FrequencyMap(Genome,k):
    n = len(Genome)
    freq = {}
    for i in range(n-k+1):
        pattern = Genome[i:i+k]
        freq[pattern] = 0
    for i in range(n-k+1):
        pattern = Genome[i:i+k]
        freq[pattern] += 1
    return freq

print(*clumpfinding("CTAGGTCAGCTACCTAGATCTACACAGGACTCACATCAGGACTCACATATGCCATGCGGTAAAAGTGTTCCCAGGCACAGGACTCACACAGGACTCACGCAGGACTCACACTTCTACAAGGCGCAAGTGTCCGTTTGGGCTTATAGTTTGGGCTTTCTGAAATGAAGTTTGGGCTTACGGTTTGGGCTTCTTTTTGGGCTTCCAGTTTGGGCTTGACTCTCTTTCGGGCGCATGAATCGCAATTTAAACTTCTTGAATGAACAGATGGTGATAAATCATGCCCTAGTCCATGGTAGGAAAACTTGCAAAGCGAGTTGTGCGAACGTGACATTGCCAACGGAGGGCACGTGGGAGAGCTGGGTAGGAGAATCCCTCTCTGTCAAGTTCCTCCGCGGGGCGCTGTTCCATTATACGGACAAAGCATTAGTTGAGTGAGGAAATAAGGCATTAATTAGTTGAGATTAGTTGAGACAAATTAGTTGAGACCCACAGTGTGAACAACGGTCTTATCACAGCTGCCGACCACGCGGACCTTCTCATGTAAAGCCATCGGTGTAGGGCTAACGGGTGGTCTTGGAGGTAGTTCTAATGGACCGCGAGCACAACCGGTTCAGAGAAAATCTGAGGGCCGTGTCAGCTATTCTTATGCAAGGGTAGTAATGTTTTCATATCTGCCTGATTTTCAATTGTCAAACGGATTCGTCGGGCCAGAAGAAGCAAAGCCATAACAAGCCTTATGTCACTTGTCACTTTGAAGAAACCTTGTGTCACTTTGTGTTTCAGATAGCAGACCCACGTGTGTCACTTTGTCACTTTGTGTCTGTCACTTTGTTTAAAATCTCGACGCCGATTAAATCTCGACCTAAATCTCGACAATGCTAGATCAGTCTCGCAAACATAATATTCGAAAATCTCAAATCTCGACTCGTATGTTCTACAAAGGCTAGGGCAGGCTCTTTGTTCTTTGTGTTTGAGGACCTTGTCTGCGGTCGATGGCTCGGCTCTGGCTCTTTGTTGGACGGATGGACGGAGGCTCTTTGTCCGTTGGACGGATAATAATTCAGTTGCGTGGACGGATATGATAGCTGATCGATGAGGCCCCCAAGGCCAGGCCCCCAGCACAGGCCCCCAAGGCCCCCAGACACAAACTATCATCAGGCAGGCCCCCAGAAGGCCCCCAGTATCACCTTCACTTCTTAGGGTGCACCTCGGTGCGACGATTAACGGTGCGGTCGGTGCGACGAAGACCGGTGCGACCGGTGCGACGGACGAAATATCCTGGAGTTGACGGTGCGACGAGCTTTCGGTCATTGGCGCTGTTTCATCTGCAGTGGCGCCGGTACCCCATTCTCGTAAGATGGAGTCTGTGGTTGATACATATGAGCCTACTACGCACTGAGTATACTCGCTATCGTGTGGTTCTCGCCCTCGGTGTAGTCGAGAAATCCAGCTGAAATCGTGACAAGCTCAGCGGACTCCGGCTAAAGAGTAAAATTGCTGGGTTGTTGCGCTGCTCTAACAGACTCGGGTGTGAACGAGAGGATCTCCACATCGCCTACCGCTGACCAGGAAATATACCTAGGCATATCCCCTGGGAGGCTCTATTTTAAGCGCGGGCGTCAGACCTGTGTCGTAGGGCCTCCCGATCTGTCATTACATTACTGCGGTTAATATGGAACGGAGAGTCACGACTCTTGGCACGTAAGGCCAGGCCTATGGCTGGAACGTAGCAATAAAGTTAACTTAGCCGGAATCTAGCCCCTATTGGACAAAGGATCGTTTAACATATCGGACCGCCCCCTAGTCCATCTCATGCCCATAGTGTGGTCTTAACCGTACCATCTCATGCCCCATCTCATGCATCTCATGCATGCCCTCATGCTTGTGACCGAGCGGGATAAAGGCATATGTGGGTGTTTCGTCAGCTACCCATAGTGTTCACAGGTAAGGGCAAGTGCCTTAGCTGTGGAGCTCGAGTGTAATCTAACATATTGTTTAAC",10,100,4),sep = " ")

